const data = {
  products: [
    {
      name: 'David Bartus shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'David Bartus',
      rating: 4.5,
      numReviews: 10,
      description: 'Tailored from luxurious fabric with meticulous attention to detail, combining sophistication and comfort effortlessly..',
    },
    {
      name: 'Pixabay Sofa',
      category: 'Shirts',
      image: '/images/Sofa1.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Pixabay',
      rating: 4.0,
      numReviews: 10,
      description: 'Stylishly modern with plush upholstery, ergonomic design, and sturdy construction for ultimate comfort and durability',
    },
    {
      name: 'Mufti Slim Pant',
      category: 'Pants',
      image: '/images/pant1.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Mufti',
      rating: 4.5,
      numReviews: 14,
      description: 'Elevate your style effortlessly with these sleek, tailored trousers. Comfort meets trend in every stitch.',
    },
    {
      name: 'Sony Headset',
      category: 'Headset',
      image: '/images/Headset1.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Sony',
      rating: 4.5,
      numReviews: 10,
      description: 'Advanced audio technology, ergonomic design, noise-canceling, and wireless connectivity for superior immersive sound and comfort',
    },
    {
      name: 'ASUS Zen Mobile',
      category: 'Mobile',
      image: '/images/mobile1.jpg',
      price: 65,
      countInStock: 5,
      brand: 'ASUS',
      rating: 4.5,
      numReviews: 10,
      description: 'Sleek design, powerful performance. Capture lifes moments with precision. Your everyday companion for seamless connectivity and style.',
    },
    {
      name: 'Apple XR Iphone',
      category: 'Mobile',
      image: '/images/iphone1.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'Meet the Apple XR iPhone – sleek design, stunning display, and powerful performance in one pocket-sized marvel. Elevate your experience!',
    },
    {
      name: 'Valeria Boltneva ',
      category: 'Watch',
      image: '/images/Watch2.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Valeria',
      rating: 4.5,
      numReviews: 10,
      description: 'Radiant with rose gold accents, a mother-of-pearl dial, and exquisite Swiss craftsmanship.',
    },
    {
      name: 'Apple mac Book',
      category: 'Laptop',
      image: '/images/img3.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'Meet the sleek and powerful Apple MacBook – your creative companion with stunning design and lightning-fast performance. Elevate your experience!',
    },

    {
      name: 'Dell Laptop',
      category: 'Laptop',
      image: '/images/img4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Dell',
      rating: 4.5,
      numReviews: 10,
      description: 'Sleek design, blazing speed, and vibrant display for work or play. Elevate your tech game effortlessly!',
    },
  ],
};
export default data;
